[project]
name = "recommender-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bentoml>=1.3.19",
    "tensorflow==2.12",
    "zenml==0.70.0",
]
